version: '3.1'

services:
    postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: fastapi
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "a@b.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 5050:80
        depends_on:
            - postgresql
